// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CSTOJS_VS_Ext
{
    internal sealed partial class Vsix
    {
        public const string Id = "CSTOJS_VS_Ext.8e348e42-b8f5-49a7-9b15-2740cb09270a";
        public const string Name = "CSTOJS for VS";
        public const string Description = @"VS Extension for CSharpToJavaScript library, using CLI. ";
        public const string Language = "en-US";
        public const string Version = "0.0.1";
        public const string Author = "TiLied";
        public const string Tags = "csharp, conversion, javascript, cs, js, generating";
    }
}
