// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CSTOJS_VS_Ext
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string uiContextSupportedFilesString = "16176706-f0dd-40c2-86ef-a3d9cba98e7c";
        public static Guid uiContextSupportedFiles = new Guid(uiContextSupportedFilesString);

        public const string CSTOJS_VS_ExtString = "b05b13b9-d1cd-413d-b435-d4a11e7b095b";
        public static Guid CSTOJS_VS_Ext = new Guid(CSTOJS_VS_ExtString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MyCommand = 0x0100;
    }
}